// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hntx.proto

package org.newtonproject.newtoncore.android.proto;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hntx.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string DAppId = 1[json_name = "dapp_id"];</code>
   */
  java.lang.String getDAppId();
  /**
   * <code>string DAppId = 1[json_name = "dapp_id"];</code>
   */
  com.google.protobuf.ByteString
      getDAppIdBytes();

  /**
   * <code>string serialNo = 2[json_name = "serial_no"];</code>
   */
  java.lang.String getSerialNo();
  /**
   * <code>string serialNo = 2[json_name = "serial_no"];</code>
   */
  com.google.protobuf.ByteString
      getSerialNoBytes();
}
