// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hntx.proto

package org.newtonproject.newtoncore.android.proto;

public final class HNTx {
  private HNTx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hntx_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hntx_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhntx.proto\022\004hntx\"<\n\004Data\022\027\n\006DAppId\030\001 \001" +
      "(\tR\007dapp_id\022\033\n\010serialNo\030\002 \001(\tR\tserial_no" +
      "B6\n&org.newtonproject.newpay.android.pro" +
      "toB\004HNTxP\001Z\004hntxb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hntx_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hntx_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hntx_Data_descriptor,
        new java.lang.String[] { "DAppId", "SerialNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
